"""
Lean runner stub.
Centralize Lean invocation + error parsing here.
"""
from __future__ import annotations
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from rich.console import Console
import logging

console = Console()



@dataclass(frozen=True)
class LeanResult:
    compiled: bool
    proved: bool
    time_ms: int
    error_type: str
    stderr_tail: str

def _find_lean_project_root() -> Path | None:
    root = Path(__file__).resolve().parent.parent / "lean"
    # Check for both lakefile formats (TOML and Lean DSL)
    if (root / "lakefile.toml").exists() or (root / "Lakefile.lean").exists():
        return root
    return None

def check(proof_text: str, timeout_sec: int) -> LeanResult:
    """
    Run Lean on either:
      (A) a full theorem text containing ':= by', or
      (B) a tactic-only block (no ':= by'), which we wrap into a dummy theorem.

    Notes:
    - Fails closed on "sorry".
    - Strips common markdown fence artifacts (```).
    - Uses --json, so diagnostics are primarily on stdout; we also include stderr.
    """
    # 0) Hard fail on sorry
    if "sorry" in proof_text.lower():
        return LeanResult(
            compiled=False,
            proved=False,
            time_ms=0,
            error_type="sorry",
            stderr_tail="Proof contains 'sorry' placeholder",
        )

    # 1) Strip common fence artifacts that break Lean parsing
    #    (handles dangling closing ``` with no opening fence)
    cleaned = proof_text.strip()
    if "```" in cleaned:
        cleaned = cleaned.split("```", 1)[0].rstrip()
    # also remove any remaining fence lines (defensive)
    cleaned_lines = []
    for line in cleaned.splitlines():
        if line.strip().startswith("```"):
            break
        cleaned_lines.append(line)
    cleaned = "\n".join(cleaned_lines).strip()

    if not cleaned:
        return LeanResult(
            compiled=False,
            proved=False,
            time_ms=0,
            error_type="malformed_output",
            stderr_tail="Empty proof text after sanitization",
        )

    # 2) Build Lean source: full theorem vs tactic-only
    if ":= by" in cleaned:
        lean_src = "import Mathlib\n\n" + cleaned.rstrip() + "\n"
    else:
        # Treat as tactic block; ensure it’s indented so Lean parses it as tactics
        tactic_block = cleaned.rstrip("\n")
        # If user/model forgot indentation, indent non-empty lines
        indented = []
        for ln in tactic_block.splitlines():
            if ln.strip():
                indented.append("  " + ln)
            else:
                indented.append("")
        tactic_block = "\n".join(indented).rstrip() + "\n"

        lean_src = (
            "import Mathlib\n\n"
            "theorem AutoGenerated : True := by\n"
            f"{tactic_block}"
        )

    start_ms = int(time.time() * 1000)

    temp_path = None
    try:
        # 3) Write temp Lean file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lean", delete=False) as f:
            f.write(lean_src)
            temp_path = f.name

        project_root = _find_lean_project_root()
        if project_root:
            cmd = ["lake", "env", "lean", "--json", temp_path]
            cwd = str(project_root)
        else:
            cmd = ["lean", "--json", temp_path]
            cwd = None

        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
        )

        elapsed_ms = int(time.time() * 1000) - start_ms

        # 4) With --json, stdout contains structured diagnostics; stderr may still have noise.
        out = proc.stdout or ""
        err = proc.stderr or ""
        combined = (out + "\n" + err).strip()

        compiled = (proc.returncode == 0)
        proved = compiled  # sound under your assumptions

        # 5) Error classification (heuristic)
        error_type = "ok" if compiled else "unknown"
        if not compiled:
            cl = combined.lower()
            if "unknown tactic" in cl:
                error_type = "tactic_error"
            elif "type mismatch" in cl or "type error" in cl:
                error_type = "type_error"
            elif "failed to synthesize" in cl:
                error_type = "typeclass_error"
            elif "timeout" in cl:
                error_type = "timeout"
            elif "invalid syntax" in cl or "unexpected token" in cl:
                error_type = "syntax_error"

        # 6) Tail for debugging (prefer combined because stdout has json diagnostics)
        lines = combined.splitlines() if combined else []
        stderr_tail = "\n".join(lines[-40:]) if lines else ""

        # Optional debug print
        console.print(f"=== Lean Proof Check (sanitized) ===\n{cleaned}\n=== End Proof ===")

        return LeanResult(
            compiled=compiled,
            proved=proved,
            time_ms=elapsed_ms,
            error_type=error_type,
            stderr_tail=stderr_tail,
        )

    except subprocess.TimeoutExpired:
        elapsed_ms = int(time.time() * 1000) - start_ms
        return LeanResult(
            compiled=False,
            proved=False,
            time_ms=elapsed_ms,
            error_type="timeout",
            stderr_tail=f"Lean execution exceeded {timeout_sec}s timeout",
        )

    except Exception as e:
        elapsed_ms = int(time.time() * 1000) - start_ms
        return LeanResult(
            compiled=False,
            proved=False,
            time_ms=elapsed_ms,
            error_type="unknown",
            stderr_tail=str(e),
        )

    finally:
        if temp_path is not None:
            try:
                Path(temp_path).unlink()
            except Exception:
                pass
